### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by hel1ow0r1d** [mattCarapella/AnotherWorld#21]
When logged in, change the session value in database from 0 to 1. When exiting, change it from 1 to 0. Languages you need to know/understand: C#, PHP, Mysql

**Comment by ayoola00** [comment]
how do i know when the user has logged in?

**Comment by hel1ow0r1d** [comment]
When the user successfully entered the correct information, that's when you know the user logged in. Let me give you a bit more information. 

If you look into the Login.cs (which is located in AnotherWorld/Another.World/Assests/scripts), you'll see that the C# script is sending information to the PHP Script known as Login.php, which is running into the server (located in AnotherWorld/PHP Scripts). Once the PHP Script checks and verifies whether the information is correct, it'll send an output to the C# Script and that's how you know the whole Login is successful or not.

Our database has a table named "users" and has 5 column. The columns are: id, session, username, email and password. The session column has a Boolean datatype. Right now, our session column is doing nothing. What we want you to do is, when the Login is successful, change that value to 1. When the player exits using the exit button (once you enter the universe and you press the Esc button, you'll see the exit button), change that value to 0 before terminating the application. We want you to change the session value using the user id.

You don't need access to our database, since we always work locally before putting it up on our production server. You can download XAMPP and configure the server the way you want, and the database the way I told you. If you have any more questions, let me know.

**Comment by ayoola00** [comment]
What do I need to start working ASAP?

**Comment by hel1ow0r1d** [comment]
You'll need the following:

1) Unity 2017.3.1f1 (Make sure you use this exact version of Unity)
2) XAMPP 7.2.3 (Will come with the latest version of PHP, MySQL and Apache)
3) Visual Studio (When you install Unity, it will automatically install)
4) A browser (you can use phpmyadmin that comes with XAMPP, to see how the database is behaving. You can also use localhost/Login.php to see if there are any errors. I would recommend you comment out error_reporting(0) to see details of the error)

Download the code from our repo and open Unity using the Another.World folder.

On XAMPP, place the PHP Scripts in xampp/htdocs and you can start working.

On Login.cs, change the URL to localhost/Login.php or whatever your URL comes out to be for testing.

**Comment by hel1ow0r1d** [comment]
Copy the code below, and replace the current Login.php with the one I gave you below. In the database, passwords are stored as SHA256. Ignore the OpenSSL encryption and decryption stuff that I put. Those are production stuff. For your testing, I am making it simple and just use SHA256 for it.
----------------------------------------------------------------------------------------------------------------
<?php

$db_host = "localhost";
$db_username = "root";
$db_password = "";
$db_name = ""; // Whatever your database name is
$conn = new mysqli($db_host,$db_username,$db_password,$db_name) or die(mysqli_error());

$user_email = $_POST[htmlentities("emailPost")];
$user_password = hash('sha256', $_POST[htmlentities("passwordPost")]);

if ($user_email != "" && $user_password != "") {
    
    $sql = "SELECT id, username, password FROM users WHERE email = ?";
    
    $stmt = $conn->prepare($sql);
    $stmt->bind_param('s', $user_email); // bind parameters for markers
    $stmt->execute(); // execute query
    $stmt->bind_result($id, $username, $db_password); // bind result variable
    $stmt->store_result(); // fetch value
    
    if ($stmt->num_rows == 1) {
        if ($stmt->fetch()) {
            if ($db_password == $user_password) {
                echo "IN;".$id.";".$username.";".$user_email;
            } else {
                echo "Wrong Password";
            }
        }
    } else {
        echo "User does not exist";
    }
    $stmt->close();
} else {
    echo "Email and/or Password cannot be empty";
}
$conn->close();

**Comment by ayoola00** [comment]
Thank you very  much, how much php or sql do i need to know to finish this issue?

**Comment by ayoola00** [comment]
This is late and yet strange but what file am I editing?

**Comment by ayoola00** [comment]
How does one go about editing the table, to see if a user is logged in

**Comment by hel1ow0r1d** [comment]
I think now's a little too late to do this, the deadline was at 4pm. I don't mind you doing this, but Jesse will not give you credit for this for doing it now. If you still want to do it, let me know.

**Comment by hel1ow0r1d** [comment]
This help wanted was not completed by the assignee and it's past the deadline. The issue is now closed.
