### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by mattCarapella** [mattCarapella/AnotherWorld#22]
Create a running count of concurrent users who join a room and use that number to spawn them in distinct locations. There can be up to 20 users in a room at a single time and each must spawn in a different location. Player game objects are instantiated in Assets/Scripts/PhotonNetworkManager.cs. There is currently only one spawn point for all users who join a room, which can be found in the Unity Hierarchy.

**Comment by darasy** [comment]
Hi. I'd like to ask on how can I know when the users join the room? Is it done in PhotonNetworkManager.cs? Also, I could not find that file in Assets/Scripts.

**Comment by darasy** [comment]
So you mean OnJointRoom instead of OnJoinedLobby since the line you mentioned on Github is in that function? Also, for every 20 people entering the room, I set the SpawnPoint.position randomly?

**Comment by darasy** [comment]
Is there any list or array of positions where the spawnPoint.position supposed to choose from? or can I simply set it randomly?

**Comment by darasy** [comment]
So what I do is 
1. I create an int variable to count the number of times the OnJoinedRoom is called.
2. when it reaches 20, I set spawnPosition.position to select random X and random Y.

**Comment by mattCarapella** [comment]
Good job. Thank you for your help.
