### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by xuanyudo** [mattCarapella/AnotherWorld#23]
Make a bug report button

Change one of the Button to Report Bug, which will open a new UI with a input field for user to edit.
![normal](https://user-images.githubusercontent.com/22279235/38056714-40ee6e22-32ab-11e8-8fa2-e119e18d8082.PNG)
and submit button to post data to server.
So non-technical people who is using our application are able to report bug to our developer.

**Comment by xuanyudo** [comment]
Thanks, I will look into it.

**Comment by xuanyudo** [comment]
What is your UBIT name?

**Comment by mjholder** [comment]
Mjholder
