### ISSUE TITLE
[Bug]The setting window is blocked by the objects in the world

### ISSUE THREAD

**Issue by z28980361** [mattCarapella/AnotherWorld#29]
Description: When you are in any world, and you are trying to exit or change setting, you clicked [Esc] key, the setting window will block by the objects in the world if there are some object in front of your view. The image below should clearly show this bug:
This is what it should be: 
![normal](https://user-images.githubusercontent.com/22279235/38056714-40ee6e22-32ab-11e8-8fa2-e119e18d8082.PNG)
This is what happened when there are objects in front of you:
![bug](https://user-images.githubusercontent.com/22279235/38056774-7060bc14-32ab-11e8-994d-7de86907eb5e.PNG)
Ground can also block this window:
![bug2](https://user-images.githubusercontent.com/22279235/38056794-7d98ecee-32ab-11e8-8049-c83fc8727da0.PNG)
Reproduce Bug:
Start the software with default setting, login, and enter any world, click on [Esc] key when there are some objects in font of you. This bug will emerge

**Comment by hel1ow0r1d** [comment]
Thanks for notifying us about the bug. We'll try to fix this issue as soon as we can.
