### ISSUE TITLE
when go back to universe from a world, all the original world in universe missed!!!

### ISSUE THREAD

**Issue by jianzhaojohn** [mattCarapella/AnotherWorld#30]
you can go to a world with no problem, but when you try to go back to universe. you will realized all the worlds that were in the universe disappear.

how to re-produce the bug:
1)loging
2)get into a world
3)press "esc" to open option
4)press "universe" to go back to universe
5)here is the bug, all worlds disappear

[bug.gif](https://media.giphy.com/media/fefRCsLO1BvmD1hzQx/giphy.gif)

**Comment by hel1ow0r1d** [comment]
Thanks for notifying us about the bug. We'll look into this problem and try to fix it.

**Comment by xuanyudo** [comment]
problem fixed
