### ISSUE TITLE
[Bug] Multiple Windows Mashed Up

### ISSUE THREAD

**Issue by hel1ow0r1d** [mattCarapella/AnotherWorld#31]
To replicate the bug:
1) Face a world, and make sure the world is highlighted green
2) Press Space
3) Then Press F

Then you are stuck in mashed up of windows. If you press the confirm button, one window stay up OR if you press the back button, then the other window stay up.

Screenshots are attached below.

![screenshot 464](https://user-images.githubusercontent.com/35990813/38060341-cd9034d6-32d9-11e8-8f10-0f4a752629e6.png)
![screenshot 465](https://user-images.githubusercontent.com/35990813/38060340-cd63f7ae-32d9-11e8-8d92-c50e6d3f9b1e.png)
![screenshot 466](https://user-images.githubusercontent.com/35990813/38060342-cdaf4696-32d9-11e8-9ed4-95e3b3d42c5e.png)

**Comment by xuanyudo** [comment]
problem fixed

**Comment by xuanyudo** [comment]
Menu doesn't go off when create world from menu option.
