### ISSUE TITLE
[Alpha Testing]  Trivial Bug: Cannot see cursor on Windows

### ISSUE THREAD

**Issue by joshuaemer** [mattCarapella/AnotherWorld#49]
OS: Windows 10
Release: Alpha v0.2.3
Description:
 In a window that did not take up the entire screen I was unable to see my cursor. This was a problem as I could not tell when my cursor was outside of the window and clicking out of the window would minimize the game. Since this game is supposed to be played with in VR this may not be an issue.

How to reproduce:
When you run the game check the Windowed check box.
Login and create a world.
You will not be able to see your cursor or tell when it is outside of the game screen.

This bug was submitted as part of the Alpha Testing section of the collaboration phase.

**Comment by xuanyudo** [comment]
Hi joshuaemer,
I was trying to reproduce this bug. You click the mouse when mouse is outside of the application, it will change the focus of your machine. It happens in all other application. Or can you provide more precise detail of this bug.

**Comment by joshuaemer** [comment]
Maybe I shouldn't have called it a bug but a feature request to be able to see your cursor. I understand if you click outside of the application it will close the screen. The problem I was having was I couldn't see my cursor so I couldn't tell when it was outside of the game window thus resulting in clicking outside of it. Feel free to interprete this as either a feature request or a bug.

**Comment by hel1ow0r1d** [comment]
Issue has been fixed in the latest release.
