### ISSUE TITLE
[Critical Bug] Game gets stuck every time after joining in

### ISSUE THREAD

**Issue by RedwanIbneSerajKhan** [mattCarapella/AnotherWorld#52]
# Description

I tried to run the game, but it gets stuck every time after I join in.

# Picture of the issue

![major bug another world](https://user-images.githubusercontent.com/28854577/38825380-5f5598b2-417a-11e8-8a39-4737695aaff5.jpg)

**Comment by xuanyudo** [comment]
We will look into this bug, thank you for reporting bug.

**Comment by xuanyudo** [comment]
checkout our newest version 0.3.1.
