### ISSUE TITLE
[MINOR BUG] Button display

### ISSUE THREAD

**Issue by shallyguo** [mattCarapella/AnotherWorld#70]
When I view the buttons again after placing the blocks in my virtual world, Some of the buttons are hidden when they are overlapped with the block pieces. This can be shown in the image below. 

![bug](https://user-images.githubusercontent.com/31744330/39065204-06a16fc0-449f-11e8-8463-c5870d999efe.PNG)

**Comment by hel1ow0r1d** [comment]
Hi @shallyguo. this bug was already reported a long time ago in issue #29. We already fixed this issue in v0.3.0 and later. Thanks for reporting the bug regardless.
