### ISSUE TITLE
[Bug] Pressing ESC in Settings screen causes bug

### ISSUE THREAD

**Issue by jzeng4ub** [mattCarapella/AnotherWorld#71]
![image](https://user-images.githubusercontent.com/35944077/39069649-65e9d972-44ae-11e8-857b-93821008fedc.png)

It keeps the old settings buttons open but also opens up the previous menu as well.

**Comment by hel1ow0r1d** [comment]
Thanks for reporting the bug. We'll look into it and fix it in future release.

**Comment by xuanyudo** [comment]
Bug Fixed
